plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pete.sudoku'
    compileSdk 35

    signingConfigs {
        stableDebug {
            storeFile file('../.signing/pete-sudoku.keystore')
            storePassword 'pete-sudoku-2026'
            keyAlias 'pete-sudoku'
            keyPassword 'pete-sudoku-2026'
        }
    }

    defaultConfig {
        applicationId 'com.pete.sudoku'
        minSdk 23
        targetSdk 35
        versionCode 8
        versionName '2.6'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableDebug
        }
    }
}
